#!/bin/sh

brand_root="$1"
jail_root="$2"

. ${brand_root}/../shared/utils.sh

validate_root "${jail_root}"

# outer jail
umount ${jail_root}/root/dev
# inner jail
umount ${jail_root}/root/jail/dev

umount ${jail_root}/root/jail/proc
umount ${jail_root}/root/jail/sys
