#!/bin/sh

brand_root="$1"
jail_root="$2"

# include shared utility functions
. ${brand_root}/../shared/utils.sh

validate_root "${jail_root}"

clean_outer_root "${jail_root}"

# create bas

dirs="bin dev mnt proc tmp etc/defaults"
for dir in ${dirs}
do
    mkdir -p ${jail_root}/root/${dir}
    chown root:wheel ${jail_root}/root/${dir}
    chmod 775 ${jail_root}/root/${dir}
done

cp /etc/defaults/devfs.rules ${jail_root}/$ID/root/etc/defaults

## required files:
execs='/libexec/ld-elf.so.1 /usr/bin/fgrep /bin/sh /sbin/ifconfig /sbin/route /usr/sbin/jail'
files=""
## inlcude libraries that are needed
for e in ${execs}
do
    files="${files} $(ldd -a $e 2> /dev/null | awk '/=>/{print $(NF-1)}')"
    files="${files} ${e}"
done

## copy the files in the zone root
for file in ${files}
do
    mkdir -p ${jail_root}/root$(dirname ${file})
    cp ${file} ${jail_root}/root${file}
done

# install the branch information

install_brand_files ${brand_root} ${jail_root}

install_etc_resolv_conf ${jail_root}

install_authorized_keys ${jail_root}

#TODO: network config:
# * routs? (do we need to set them?)
#TODO: get rood autorized keys set set them
