#!/bin/sh

# include shared utility functions
inner_id="$1"

# cleanly shut down the inner jail (should this be run inside the outer jail?)
if [ ! -z "${inner_id}" ]
then
    jexec ${inner_id} /bin/sh /etc/rc.shutdown
fi
