#!/bin/sh

if [ ! -d /usr/local/etc/vmadm  ]
then
    mkdir -p /usr/local/etc/vmadm
fi

if [ ! -f /usr/local/etc/vmadm.toml  ]
then
    cp /usr/local/lib/vmadm/vmadm.toml.example /usr/local/etc/vmadm.toml
fi

if [ ! -d /var/imgadm/images ]
then
    mkdir -p /var/imgadm/images
fi
